package test.IEcho

struct TestStructure {
    UInt64 param1;
    UInt32 param2;
}

struct TestStructureBig {
    TestStructure param1;
    UInt32 param2;
}

const UInt32 TestStringSize = 5120;
typedef string<TestStringSize> TestString;

interface
{
    Echo(in TestStructureBig input, out TestStructureBig output);
}
